### ISSUE TITLE
I don't think scrolling should get rid of the title

### ISSUE THREAD

**Issue by Twinters007** [frc1418/frc1418.github.io#102]
It'd be nice to have either "Vae Vicits" or "FRC Team 1418 - George Mason High School" when you scroll. There's enough space to look good - especially for the latter as it'll take up more of the bar -  and you wouldn't have all that blank space.

Another thought, don't make it jump, but rather transition?

**Comment by ErikBoesen** [comment]
It's in the works, a la Adrian. We needed to merge now so that Adrian could have something to point to when Ballou inevitably grilled him this afternoon about what he's working on.

**Comment by Twinters007** [comment]
Pushing to master doesn't seem like the best solution, but at least its being worked on
