### ISSUE TITLE
Nitpicky Things

### ISSUE THREAD

**Issue by Twinters007** [frc1418/frc1418.github.io#103]
https://github.com/frc1418/frc1418.github.io/blob/master/_pages/contact.html#L12
team 1418 -> Team 1418

https://github.com/frc1418/frc1418.github.io/blob/master/_pages/contact.html#L21
email -> Email

https://github.com/frc1418/frc1418.github.io/blob/master/_pages/robot/2014.html#L19
cim -> CIM

There are sure to be more. I just did a quick run though and this is what I caught

**Comment by ErikBoesen** [comment]
@aderhall @steved14000

**Comment by ErikBoesen** [comment]
Since nobody else seems to want to do this, I'll be done in a minute
