### ISSUE TITLE
Add 2010 robot to robots page

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#116]
Grab a screenshot from one of these videos:
https://www.thebluealliance.com/match/2010va_f1m1
https://www.thebluealliance.com/match/2010va_f1m2

At one point there was also a photo in Mr. Ballou's workshop. If it's still there someone should snap a picture of it to add here.

**Comment by Twinters007** [comment]
Don't screenshot a video

**Comment by ErikBoesen** [comment]
@Twinters007 Why not? We don't have much other choice.

**Comment by Twinters007** [comment]
Cricket can probably find some parents who took photos that year.

**Comment by ErikBoesen** [comment]
I'll check with her. I asked Ballou several times, but he didn't give anything.

**Comment by ErikBoesen** [comment]
@ianzullo @AndrewLester

**Comment by ianzullo** [comment]
@ErikBoesen Do we have pictures or do you just want us to screenshot those videos?

**Comment by ErikBoesen** [comment]
For now, just screenshot the videos. Finding better photos sort of falls under #37, anyway.
