### ISSUE TITLE
Hamburger menu opens randomly on mobile when scrolling down

### ISSUE THREAD

**Issue by ianzullo** [frc1418/frc1418.github.io#119]
(Also works when window is shrunk)
![screen shot 2017-11-28 at 3 56 20 pm](https://user-images.githubusercontent.com/15891996/33343816-b33ebec4-d454-11e7-8945-27d1eac2cca3.png)

**Comment by ErikBoesen** [comment]
Is this resolved? @ianzullo

**Comment by ianzullo** [comment]
Yes, this is resolved.
