### ISSUE TITLE
Updated bios needed for new members

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#143]
Also, Ethan isn't a programmer.

**Comment by ianzullo** [comment]
He used to be and it slipped me when I was writing his description

**Comment by ErikBoesen** [comment]
Yeah, no problem. Just something to clarify next time around.

**Comment by addisonr08** [comment]
This issue seems small and mostly complete, if anything add it to various tasks. Close @ErikBoesen

**Comment by ErikBoesen** [comment]
@addisonr08 This is ongoing, there are still plenty of members with one-line bios. Also, it's typically good practice on GitHub to keep separate issues separate.

**Comment by ErikBoesen** [comment]
Can someone just walk around at a meeting and get people to type new bios in for themselves?
