### ISSUE TITLE
Issues that need addressed.

### ISSUE THREAD

**Issue by THIRTY9CLUES** [frc1418/frc1418.github.io#145]
New Website
New Team pic (the one from last year)
New Gif (Go pro footage taken from last year)
Full info for the The Team page
Get rid of the Calender section
Repetition in the Udvar-hazy section of the Outreach.

**Comment by ErikBoesen** [comment]
1. Unsure what you mean.
2. To my knowledge we have no full-team pic from last year.
3. We don't have this either and don't need to update our background video.
4. See #143 
5. Cricket wants it to remain, though I'm fine with removing it. I just opened #146 on this topic.
6. See #147.
