### ISSUE TITLE
Keep 2018 page up to date

### ISSUE THREAD

**Issue by NathanielHorne** [frc1418/frc1418.github.io#148]
~~Going through the website code, I found that the pages pertaining to the robots are consistently off by one.~~

~~For example, the documentation for the page for the 2017 robot is under the file 2018.html. Though I would just go and change the names of the files, lines of code in other documents refer to these pages.~~

~~I need someone to go through and change the names of the names of the pages in the appropriate places.~~

This was not actually the case.

**Comment by ErikBoesen** [comment]
This is only true of the 2018 page, which is a clone of 2017 for which we haven't updated the metadata yet.

**Comment by NathanielHorne** [comment]
It seems you know more of this than I do. Do you think you can can fix this particular issue?

**Comment by NathanielHorne** [comment]
I've already started to work on the 2018 page, it still needs work though. Please pull those edits.

**Comment by ErikBoesen** [comment]
Make a pull request if you want me to merge something.

**Comment by NathanielHorne** [comment]
I've already started to work on the 2018 page, it still needs work though. Please pull those edits.

**Comment by ErikBoesen** [comment]
It would be nice if we could get a nice background style like we had in 2017. We can talk about this in more detail. @NathanielHorne

**Comment by NathanielHorne** [comment]
Sure thing.

**Comment by addisonr08** [comment]
@NathanielHorne please remove Booz Allen from the sponsor area, we have confirmed we will not be receiving money from them this year.

**Comment by ErikBoesen** [comment]
_Anuragi wtf_

**Comment by ErikBoesen** [comment]
@addisonr08 We got $2000 from them, so they'll stay.
