### ISSUE TITLE
Add link to arcade instructions

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#155]
Currently, there's a link written on our pit Arcade to instructions at `carterfendley.com/masonarcade`. We should host these instructions (or a similar redirect to Carter's) on the team website.

**Comment by NathanielHorne** [comment]
How would you like the arcade to the website? A whole webpage on the website? A PDF embed on an existing webpage?

**Comment by ErikBoesen** [comment]
@NathanielHorne I think the best option would be to just redirect to the same place Carter's website does. Check this out: https://blog.webjeda.com/jekyll-redirect/
