### ISSUE TITLE
Assorted tasks

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#157]
From @addisonr08.

- [x] Update team picture on the home page next to the paragraph about what team 1418 is. The picture is outdated (it's from the 2016 season).
- [x] Look at potential replacement video for the background of the home page, it's also from 2016. We have time lapse footage of the team building the robot, ask Zach for that if you want it. This isn't really a necessity, the current one is fine and it's hard to tell it's from 2016, but if you can find something which you think might work better feel free.
- [x] Make sure the members page is up to date. Add in people who are active, remove people who aren’t. Talk to Addison before removing anyone.
- [x] Update the image at the bottom of the sponsorship page, it's outdated (2016). 
- [x] Update the Outreach page with information about Erik's testifying in Richmond (maybe wait on this because he's not done yet) 
- [x] Work on changing the outreach page to be more accurate by changing the tenses of words from current to past in some cases. Ex. The “Support to FIRST Senior Mentor” section. We no longer currently do that, so it needs to change from current tense to past tense.
- [x] Make sure all information in the contact page is up to date.
- [x] Spacing on the top of the resources page seems kind of off, fix if possible
- [x] We will update sponsors at a later date as we learn who will be sponsoring us in the coming season
- [x] Replace outdated pictures of the 2016 robot where applicable with the 2017 robot, at least until we do the reveal of our new bot

Here are all the pictures from the team of this season, should be helpful. All are in glorious 4K, so keep file size in mind and reduce the resolution as needed, talk with me about that.
https://drive.google.com/drive/folders/0B93fACMelk1iaUJWejJwajZNQms?usp=sharing

**Comment by NathanielHorne** [comment]
Okay. Someone please explain the background video code to me. They create the code so that the video can be read, but don't have the execution of the code or the video in the code itself. How does it work?

**Comment by ErikBoesen** [comment]
@NathanielHorne The video has no `src` attribute in the HTML. This is because we don't want to automatically load the video on mobile phones, where we don't show it and where it could waste mobile data. The `src` attribute gets added through JavaScript if the screen size is large enough to not be considered a phone, and the browser will then automatically load and play it.
