### ISSUE TITLE
Image files for 2018 page not present

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#160]
The `<img>` tags also have incorrect links.

The images should go in `/assets/img/robots/2018/` and be linked accordingly. Also, no need to capitalize them all.

**Comment by ErikBoesen** [comment]
@NathanielHorne I fixed the other two, I just need you to do this one now.

**Comment by ErikBoesen** [comment]
I want to try and help you figure out how to preview the site this afternoon... I think it will help you a lot if you can see the output.

**Comment by NathanielHorne** [comment]
Fixed.
