### ISSUE TITLE
Fix image on "sponsor us" page

### ISSUE THREAD

**Issue by addisonr08** [frc1418/frc1418.github.io#166]
Where there is supposed to be a picture of our robot, there is the text "2018 robot as of now."

**Comment by addisonr08** [comment]
@NathanielHorne

**Comment by maratmkhitaryan** [comment]
This is normal because there is no such picture! You link your image to this: http://1418.team/assets/img/2018/ROBTHREE.JPG (404 error), Where is the image that you need?
