### ISSUE TITLE
Sponsor logos should be more responsive.

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#18]

**Comment by CarterFendley** [comment]
I sorta disagree with this. The sponsors logos are just that, logos. They shouldn't be jumping around the page or doing little twirls. Its fine to make them links though.

**Comment by ErikBoesen** [comment]
No, I mean [responsive](https://en.wikipedia.org/wiki/Responsive_web_design) as in adaptable to different screen sizes. Right now they just disappear when the screen is too small to fit them. I think they should switch to a single, scrollable row or something of the sort, instead of just hiding. @CarterFendley

**Comment by ErikBoesen** [comment]
Also, for the record, they are links already.

**Comment by CarterFendley** [comment]
Oh okay gottcha. and lol didnt know

**Comment by ErikBoesen** [comment]
No problem, should have phrased it better
