### ISSUE TITLE
Link competition schedule!

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#182]
It's on https://thebluealliance.com/team/1418. It would be nice if we could refer people here on the homepage or somewhere else.

**Comment by addisonr08** [comment]
Would we want this schedule to be interactive and will we want to feature it in the upper bar between "the team" and "sponsor us"? Or put it under "more"?
@ErikBoesen

**Comment by ErikBoesen** [comment]
Hmm... I don't know. Embedding the schedule sounds like a neat idea... I should ask the TBA guys if there's any way to do something like that.

**Comment by ErikBoesen** [comment]
Update: I'm talking with them, it looks like this might happen.

**Comment by NathanielHorne** [comment]
Any progress on how the embed is going?

**Comment by BobbyMi11er** [comment]
@ErikBoesen Where do you want me to put the schedule?
