### ISSUE TITLE
New sponsors for footer

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#183]
All these need to be re-added. Some have logos which can be found if you go back a few months in the commit history.
![](https://user-images.githubusercontent.com/5923662/36633257-0e83e6b0-1960-11e8-9c01-e823ed24a0f3.jpg)

**Comment by NathanielHorne** [comment]
Can you send me the new GM logo? I can't find it online.

**Comment by ErikBoesen** [comment]
@NathanielHorne Go back in the commit history to a couple months ago, we had it there.

**Comment by NathanielHorne** [comment]
Thanks.

**Comment by NathanielHorne** [comment]
I have 

- SETTY
- FCEF
- BOOZ  HAMILTON
- EBT

what I need

- FAMILIES OF 1418
- TMG
- LEIDOS
- NEW GMHS SYMBOL
- NEW FCCPS SYMBOL
- AFCEA NOVA
- VEKTRE
- DIGITAL DESIGN & SERVICES INC

**Comment by ErikBoesen** [comment]
EBT and Vektre are both my company. I renamed it from the former to the latter last year. Use this logo instead of the EBT one:
![](https://raw.githubusercontent.com/Vektre/vektre.github.io/master/img/logo.png)

* For Families of 1418, just use text rather than a logo.
* TMG is The McGuire Group, which is owned by Cooper's parents. [This](https://www.themcguiregroupllc.com/) is their website, I'll ask Cooper if he's got a high res version of their logo.
* Leidos: There are a bunch of logos on Google.
* [Digital Design & Imaging Service](https://airphotoslive.com/)
* FCCPS, GM, and AFCEA Nova have logos you can find from commits before we removed them.

 @NathanielHorne

**Comment by twinters007** [comment]
Did AFCEA Nova give you guys money this year?

**Comment by ErikBoesen** [comment]
Apparently.

**Comment by addisonr08** [comment]
Flippin Pizza is doing a pizza night for the team, doesn't that qualify for the name of their business (but not their logo) on the site, or is it dependent on amount made from the fundraiser? Im under the impression its the former

**Comment by ErikBoesen** [comment]
Are there two different levels? I didn't know that. I could be wrong.

**Comment by NathanielHorne** [comment]
I'll put them as a special thanks. Should we want to, I'll put the .svg online.

**Comment by ErikBoesen** [comment]
@NathanielHorne If you haven't already, then don't bother doing so.

**Comment by NathanielHorne** [comment]
Well I put them as text, but not as an SVG. Keep it?

**Comment by ErikBoesen** [comment]
Remove them since they haven't given us enough money. We can always put them back later.

**Comment by NathanielHorne** [comment]
Sounds good.

**Comment by NathanielHorne** [comment]
What do we still have to do?

**Comment by ErikBoesen** [comment]
Nothing.
