### ISSUE TITLE
Update 3D Printing Guide 

### ISSUE THREAD

**Issue by addisonr08** [frc1418/frc1418.github.io#187]
- Update to include the latest software
- Make edits referring to newer hardware/methods if applicable
- Move from frc1418.github.io/files to frc1418.github.io/assets/resources where all other PDFs are (Erik thats you) 

Freddy can help make edits, though if someone has the original doc this can be updated easily by anyone

**Comment by NathanielHorne** [comment]
@addisonr08 By "latest software" do you mean the latest firmware for whatever printer we're using?
