### ISSUE TITLE
Use high-res logo for The McGuire Group

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#194]
The one we have now is just my attempt at making their logo on their website an SVG, it's really low res and as such our logo looks rather bloated and inaccurate. There are definitely higher res versions, we need to find one.

**Comment by ErikBoesen** [comment]
[TMG-Sign-1.pdf](https://github.com/frc1418/frc1418.github.io/files/1786641/TMG-Sign-1.pdf)
You can get it from here.

**Comment by NathanielHorne** [comment]
Didn't Erik already do this?

**Comment by ErikBoesen** [comment]
We have a slightly better one now; it's still not the very nice version.

**Comment by NathanielHorne** [comment]
Well. The one you gave me before was a PDF. When I ran it through the pdf --> svg software, it didn't render the entire thing. It was a blob. What do you suggest?
