### ISSUE TITLE
The epic climb at Battlefield

### ISSUE THREAD

**Issue by NathanielHorne** [frc1418/frc1418.github.io#197]
Someone with the power, please post the climb we did where we defeated the boss on youtube please. It's the one where two robots climbed while the other had the levitate.

**Comment by ErikBoesen** [comment]
@addisonr08 Can I get that video clip? I'll put it on YouTube.

**Comment by addisonr08** [comment]
We already have a video up featuring the climb. Additionally, in the next 2 days we will be releasing a summary video of the competition featuring that clip. I'll link the unedited upload in the description.

**Comment by ErikBoesen** [comment]
https://www.youtube.com/watch?v=G10ExgJBIGI
