### ISSUE TITLE
Text issues on 2018 page

### ISSUE THREAD

**Issue by addisonr08** [frc1418/frc1418.github.io#202]
- Text lineup is very uneven on displays larger than our macs for the first lines of text on the 2018 page. Bug, easy fix.

**Comment by ErikBoesen** [comment]
Can I get a screenshot?

**Comment by addisonr08** [comment]
Check it out on the computers in the MakerStudio tomorrow, its just an alignment issue sync it w the rest of the text on the page. @ErikBoesen

**Comment by ErikBoesen** [comment]
Ah, yup, there just isn't any element wrapping a bit of text. I'm going to go out on a limb and say Nathan won't fix this anytime soon, so I'll do it myself.
