### ISSUE TITLE
Add Newsletter to Navbar

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#205]
https://us12.campaign-archive.com/?u=116c018468396fe09157a44fe&id=958bf0e49a

**Comment by ErikBoesen** [comment]
This should be incredibly easy.

**Comment by addisonr08** [comment]
I would argue that we should add the newsletter sub link to the home page and eliminate the contact page, as the only thing on it is the newsletter

**Comment by ErikBoesen** [comment]
@addisonr08 The newsletter is a very small part of the contact page... there is also contact information for all our mentors, links to social pages, and our mailing address.
