### ISSUE TITLE
Add Twitter feed widget

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#206]
It's not that hard to do this. We'd have to think about where is best to put it, though.

**Comment by NathanielHorne** [comment]
Yeah. Would you like a link at the top or a full on embedded twitter feed?

**Comment by ErikBoesen** [comment]
@NathanielHorne I actually don't know. This is low priority, so try to fix all the Easy Fix things first.

**Comment by NathanielHorne** [comment]
@ErikBoesen Right

**Comment by JosephCarpenter** [comment]
Maybe we could make a separate news page with a twitter feed and the 1418 newsletter?

**Comment by ErikBoesen** [comment]
@JosephCarpenter The question there would be why not just link to both of those pages?

**Comment by ErikBoesen** [comment]
@JosephCarpenter The question there would be why not just link to both of those pages?
