### ISSUE TITLE
Post legal/organizational information here

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#207]
1111 Power Hawks does a really good job of keeping all their business/organizational information online (https://www.powerhawks.org/phrc-bod/, for example). It would look really good for us to do something like this.

**Comment by NathanielHorne** [comment]
How do you think we could do this? Add some text to the footer or add a separate page altogether?

**Comment by ErikBoesen** [comment]
@NathanielHorne totally separate page.
