### ISSUE TITLE
Reshuffle Team page by hours

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#226]
Based on who's contributed the most (by hours). We should take out people who haven't contributed.

**Comment by AndrewLester** [comment]
Would you say it would be better to manually order them or sort using javascript somehow? (And manually input hour data for javascript)

**Comment by ErikBoesen** [comment]
@AndrewLester Manually, mainly because the JS solution, while neat, would be unnecessarily complicated and wouldn't take into account people who just haven't put in hours yet. Plus, we'll need to also order some things based on position of the members on the team, something we'll be enforcing a lot more this year.
