### ISSUE TITLE
Add contact information for members?

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#227]
There may be privacy issues with regards to this. Maybe just for team leaders/people who've given approval.

**Comment by addisonr08** [comment]
The adults will not support this, as they will worry about harassment etc, but I am all for it. Could we make it so that when you mouse over a team member's picture, the contact info they want to share is displayed?

**Comment by ErikBoesen** [comment]
@addisonr08 Yeah that's my concern. They were worried about even putting the team contact information on the shirts, they'd probably have a fit about putting personal Twitter links up. I'm totally fine with putting my own on there, but we would need to get permission and look over whether there are legal problems.

**Comment by NathanielHorne** [comment]
Yeah this isn't a good idea. Let's leave confidentiality for the students.

**Comment by twinters007** [comment]
On account of being a mentor, I think it’s fine. If Erik wants to put his email and twitter handle on that’s fine. It’d be cool to have a member sign in that would let you get contact info for all members, since that’d be pretty helpful.

**Comment by ErikBoesen** [comment]
@ArchdukeTim Member sign in isn't really possible since this is set up as a static website.
