### ISSUE TITLE
Use high-res team photo from Championship on homepage

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#231]
Need to get this from whoever was taking photos with a good camera (not Knight).

**Comment by AndrewLester** [comment]
Zack had the camera I believe.

**Comment by NathanielHorne** [comment]
@ErikBoesen Who's that someone who took a DSLR image?

**Comment by JosephCarpenter** [comment]
And where can we find it?

**Comment by ErikBoesen** [comment]
Turns out none got taken.
