### ISSUE TITLE
Various Content Updates 

### ISSUE THREAD

**Issue by addisonr08** [frc1418/frc1418.github.io#233]
These are meant to be done and continue to be worked on as we go into the offseason
- Update season performance description on 2018 page (I'll do this)
- Make final updates to 2018 page, including maybe adding updated media
- Re-organize the team page to show team leaders at top, remove inactive members
- Update outreach page, organize chronologically, add in Erik's deans list award and work, etc
- Consider removing the "contact us" page as it is mostly redundant and relocate content elsewhere
- Update resources page and keep updated as we roll out new content in the offseason (I will handle most of this)

**Comment by ErikBoesen** [comment]
Please open future issues as different issues, not as one with a bunch of bullet points.

**Comment by ErikBoesen** [comment]
We're not removing the contact page. People go to the website specifically looking for a contact page.
