### ISSUE TITLE
Replace Dean's List photos with official ones

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#244]
The ones there now were just phone photos. They are going to release actual professional photos within a few days.

**Comment by NathanielHorne** [comment]
Do we have those images?

**Comment by ErikBoesen** [comment]
We do now. I'll stick em in

**Comment by NathanielHorne** [comment]
@ErikBoesen where can I go to find them?

**Comment by NathanielHorne** [comment]
@ErikBoesen Thanks

**Comment by ErikBoesen** [comment]
I'm putting them in there.
