### ISSUE TITLE
Add alt text for images

### ISSUE THREAD

**Issue by JosephCarpenter** [frc1418/frc1418.github.io#250]
It just occurred to me, would it be a good idea to add alt text to the images on the website for those with screen readers?

**Comment by ErikBoesen** [comment]
Yes, it definitely would. In theory we already have it everywhere for compliance with the ADA... if we're lacking it anywhere we should definitely fix that.

**Comment by NathanielHorne** [comment]
@ErikBoesen please close this, Joe has done this.
