### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#264]
We'll need to do some Cloudflare configuration things for this (and get access to Ballou's account on Hover).

**Comment by twinters007** [comment]
Let's Encrypt should be useful

**Comment by ErikBoesen** [comment]
@twinters007 Maybe... but for Pages-hosted websites I typically just forward through Cloudflare.

**Comment by twinters007** [comment]
Oh do they provide the cert?

**Comment by ErikBoesen** [comment]
Yeah, you can use theirs for free.

**Comment by ErikBoesen** [comment]
For future reference, GitHub ended up adding this as an automatic feature for pages.
