### ISSUE TITLE
Grammar of FCEF description on Outreach page is a mess

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#286]
Needs capitalization fixed and less repetition

**Comment by BobbyMi11er** [comment]
Does this look good?
"The Falls Church Education Foundation is a sponsor of FRC 1418. FRC 1418 is annually invited to the FCEF gala, which helps them maintain a continuous conversation, and provides the team an opportunity to let FCEF know what their money is being spent on. This event also gives the team a chance to promote the FIRST program, demonstrate the robot to the gala attendees, and share their recent successes."

**Comment by ErikBoesen** [comment]
@BobbyMi11er That looks terrific! PR it!
