### ISSUE TITLE
Outreach page is poorly organized

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#319]
A lot of it is outdated and out of any reasonable order. It would be nice to re-sort things, prioritize the things we've done that are more important than individual demos.

**Comment by ErikBoesen** [comment]
Perhaps it's a good idea to use multiple pages? Or maybe sort it into different outreach levels, like community/state/world?

**Comment by ErikBoesen** [comment]
@ianzullo sorry I forgot you didn't want to do the website anymore

**Comment by ianzullo** [comment]
I'm fine with still helping out with the website, i just wanted to do robot code this year since i didnt last year

**Comment by ErikBoesen** [comment]
Ah, that makes sense. I'll assign you some robot code issues to balance things out.
