### ISSUE TITLE
Change <video> in background of homepage to a GIF.

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#33]
Would probably be more efficient resource-wise, as well as easier to style. Currently, the video sometimes doesn't load and leaves the background as flat and grey, which is unsightly. This issue would probably be mitigated by turning replacing the `<video>` with a simple `<img>`.

**Comment by calebeby** [comment]
What if you just had a static image inside the video element as a fallback?

**Comment by ErikBoesen** [comment]
That was one idea I thought of, but I don't quite see the point. There's no real advantage to using a `<video>` over a GIF for this purpose.

**Comment by calebeby** [comment]
True, I suppose that there won't be much of a quality difference since
you're blurring the image.

**Comment by ErikBoesen** [comment]
Yeah, that's what I was thinking.

**Comment by ErikBoesen** [comment]
Fixed by #34
