### ISSUE TITLE
Be more specific about logo use restrictions

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#364]
It would probably be good to make it clear that we only want modifications in the context of trying to conform to game theme.

![](https://user-images.githubusercontent.com/5923662/53652754-9a2c0000-3c17-11e9-961c-fa9d5109b0e8.png)

**Comment by 1ceit** [comment]
Can we close this? 
It looks like it was fixed...
<img width="1174" alt="Screen Shot 2024-01-29 at 9 57 29 AM" src="https://github.com/frc1418/frc1418.github.io/assets/118136127/acca7354-d2ac-4145-b258-7939557a6c1b">

**Comment by ErikBoesen** [comment]
Yeah this is fine
