### ISSUE TITLE
Nav items overflow in Firefox on certain MacBook models

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#378]
I opened the website recently on Firefox Nightly on my MacBook Pro mid-2015 and found that the navbar seems to collide with the rest of the header. Might be worth looking into.
<img src="https://user-images.githubusercontent.com/5923662/65836946-cf3d2580-e2c0-11e9-9939-9c6ed16e5b4d.png">

**Comment by Git-HorizonZz** [comment]
Do you know if this is still an issue?

**Comment by ErikBoesen** [comment]
It seems to be alright now.
