### ISSUE TITLE
Fix maps API token on Alumni page

### ISSUE THREAD

**Issue by AndrewLester** [frc1418/frc1418.github.io#391]
Now that it is linked on the team members page, we should probably fix the map code.

**Comment by quirozj** [comment]
Do we pay for it? Apparently it used to be free but no longer is.

[https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors]

**Comment by quirozj** [comment]
![Screen Shot 2019-11-25 at 9 18 49 AM](https://user-images.githubusercontent.com/57964624/69548123-c38a7a00-0f64-11ea-9860-aeba15c0abc6.png)

**Comment by AndrewLester** [comment]
Yeah google now requires you to enable billing on projects, meaning someone will have to put in a credit card. It won't cost money though, as they give a 200$ credit per month for the google maps api. I'll probably make an account and put in the information.

**Comment by ErikBoesen** [comment]
Andrew is correct; you have to put in a billing method but it won't actually charge you. I currently use the API in several other places (firstmap.github.io, erikboesen.com/seniormap, a mobile app I'm developing, etc.) and it works fine. The issue with this was that I accidentally revoked the token that the alumni map was using and forgot to make it a new one, so you'll just have to make a new Maps JS API token and set up billing and all should be good.
