### ISSUE TITLE
Shadows are cropped at the bottom of banners

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#399]
I suspect some element pertaining to the banners has a limited size and doesn't allow overflow.
![](https://user-images.githubusercontent.com/5923662/71450428-a4336800-272f-11ea-8f5a-2d8401033065.png)

**Comment by BenGitsMagic** [comment]
Fixed it! (I think)

**Comment by ErikBoesen** [comment]
This does not appear to be fixed at the moment. @BenGitsMagic

**Comment by BenGitsMagic** [comment]
Oh yeah, my push needs to be accepted, but it looks good on my server`
<img width="1109" alt="Screen Shot 2022-12-06 at 4 26 11 PM" src="https://user-images.githubusercontent.com/91988767/206026632-abf8b9db-b68d-4d06-be30-0cd8acb1a409.png">

**Comment by ErikBoesen** [comment]
Got it, could you create a pull request? I don't see any
