### ISSUE TITLE
Spacing between pixel portrait and title bar is unpleasant

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#408]
I would recommend making the bar grey (like the backgrounds of the image) and then removing the space. I think it would be less harsh on the eyes that way.

**Comment by MyaTaheri** [comment]
Is the bar your referring to the rectangle that states the member's subteam or something else?

**Comment by ErikBoesen** [comment]
Yes @MyaTaheri, I think that's what I meant. Admittedly this is a personal preference.

**Comment by BenGitsMagic** [comment]
@MyaTaheri and I have decided that we are going to leave it as is, we think that it looks equally good as is. Thank you for the feedback anyway though!
