### ISSUE TITLE
Team social media

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#427]
This idea was floated a couple years ago and vetoed by Ballou for what I remember as being quite unfounded reasons. I thought it could be cool to include links to members' social media profiles (twitter or whatever) in their bios. It could be useful to help people in other teams contact specific subteams within 1418. Also would just generally be a fun CSS task!

**Comment by MyaTaheri** [comment]
It may be more uniform by contacting the 1418 Instagram or email instead of having members' social media profiles

**Comment by ErikBoesen** [comment]
Honestly in retrospect this is fair, there are probably privacy implications for this and possibly even FERPA/legal issues at hand.
