### ISSUE TITLE
"Robot Abilities" header on 2020 robot page is offset to left

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#444]
<img src="https://user-images.githubusercontent.com/5923662/97639357-0326d500-1a04-11eb-8ac8-fe17f426fb24.png">

**Comment by AndrewLester** [comment]
The issue looks like it's due to what should be a starting `<h4>` tag looking like an ending one.
This line:
https://github.com/frc1418/frc1418.github.io/blob/288918fe5385136a2fc54dc5544623c54657ff82/_pages/robot/2020.html#L26
