### ISSUE TITLE
Body font is too light on some displays

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#455]
We should consider using a more bold font for body text; it's a little hard to read sometimes.

**Comment by vansh-patel-8123** [comment]
can I fix this?

**Comment by ErikBoesen** [comment]
@vansh-patel-8123 You can if you want to, but this website is meant to be maintained by the specific student organization that it's about. If you're looking to make open source contributions, your talents might be more needed elsewhere.

**Comment by ErikBoesen** [comment]
Hmmm. This doesn't really seem to be a big issue. You could try making the body font weight a little higher and see if it looks good, but you can also leave it like it is I think

**Comment by ErikBoesen** [comment]
Actually, just tested on an older monitor, and it does look a little choppy. This screenshot doesn't quite do it justice, but it is a little unpleasant to read.

![](https://github.com/frc1418/frc1418.github.io/assets/5923662/e4186f6d-ed9c-4d3d-ac0b-e892d994e125)

**Comment by 1ceit** [comment]
I can add font-weight
