### ISSUE TITLE
All text using Adam font is shifted proportionally downward, causing odd overlaps in header and uncentered text on buttons

### ISSUE THREAD

**Issue by ErikRBjorklund** [frc1418/frc1418.github.io#50]
![vaevictusglitch](https://cloud.githubusercontent.com/assets/22671394/19175994/ade43902-8c09-11e6-871e-8cbbcfe82829.png)

A possible fix is separating the two into separate div classes? No harm in trying. As far as I can tell the glitch has only happened to me.

**Comment by ErikBoesen** [comment]
_Cringes_

It's 1418 not 1416

:joy:

**Comment by ErikRBjorklund** [comment]
My bad mistyped. _Many Cringes_

**Comment by ErikBoesen** [comment]
Oh, also, it's VictIs, not VictUs

**Comment by CarterFendley** [comment]
Closed?

**Comment by ErikBoesen** [comment]
@CarterFendley Not confirmed yet.

**Comment by ErikRBjorklund** [comment]
@ErikBoesen @CarterFendley The issue is still there. Again, this issue has only happened to me.

**Comment by ErikBoesen** [comment]
@ErikRBjorklund No, the issue has happened to other people as well.

**Comment by azwreith** [comment]
This issue is occurring because of the `Adam` font used in the `Vae Victus` heading. I suppose you'll want to keep that font so I'll add a bit of margin below the heading.

**Comment by ErikBoesen** [comment]
Finally fixed this by using Fontsquirrel's `@font-face` generator to normalize the font.
