### ISSUE TITLE
Videos on 2013 and 2012 don't work

### ISSUE THREAD

**Issue by Git-HorizonZz** [frc1418/frc1418.github.io#555]
Browsers I have tested:
- Chrome
- FireFox
- OperaGX
- Edge
- Safari

**Comment by ErikBoesen** [comment]
Seems the iframes are linking to the YouTube page itself rather than the `/embed` URL—go to the video and click Share > Embed to get code that will work properly. (You'll probably be able to trim the code down a bit.)

**Comment by MyaTaheri** [comment]
Completed with the latest pull request
