### ISSUE TITLE
Align social media icons in header better

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/frc1418.github.io#580]
I think it would look nicer if the icons were shifted upward to align better with the VAE VICTIS name.
<img src="https://github.com/frc1418/frc1418.github.io/assets/5923662/3d7b51b7-bf43-4681-a491-430fb38558a2">

**Comment by ErikBoesen** [comment]
tbh also could be worth making VAE VICTIS smaller. I don't know why I initially made it so huge

**Comment by 1ceit** [comment]
Fixed. Will push when I can.
