### ISSUE TITLE
Footer Padding Too Small

### ISSUE THREAD

**Issue by 1ceit** [frc1418/frc1418.github.io#586]
<img width="1440" alt="Screen Shot 2024-01-18 at 11 36 03 AM" src="https://github.com/frc1418/frc1418.github.io/assets/118136127/14f9c794-9352-472d-8436-99616c500b1b">

Increase footer padding:
Replace 382 - 395
```
footer
    text-align: center
    color: #666
    background: $grey
    padding: 50px
    .emphasized
        color: white
    h5
        color: white
    table
        color: white
        td
            padding: 0px
            vertical-align: middle

```

**Comment by ErikBoesen** [comment]
Would this fix it on all screen sizes?

**Comment by 1ceit** [comment]
If I made it a % then yes it would be relative.
