### ISSUE TITLE
Red Banners

### ISSUE THREAD

**Issue by MyaTaheri** [frc1418/frc1418.github.io#600]
Are we allowed to have the Blue Banners red?  Mr. Brobst was worried about copyright laws

**Comment by ErikBoesen** [comment]
This is.... not how copyright works.

**Comment by MyaTaheri** [comment]
idk, Brobst was saying it could be an issue and I wasn't sure but it seems like it isn't

**Comment by ErikBoesen** [comment]
What he might have been thinking of is that in the past, if I recall correctly, FIRST complained about people custom-printing *exact* physical copies of the blue banners. But they don't own the concept of a box on a website with little triangular tails.
